version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "5050:5050"

  user-service:
    build: ./user-service
    ports:
      - "5051:5051"

  order-service:
    build: ./order-service
    ports:
      - "5052:5052"

  notification-service:
    build: ./notification-service
    ports:
      - "5053:5053"
