apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5051
      nodePort: 30551  # Can be any open port
