apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-container
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5051
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret       # 👈 secret name from secret.yaml
              key: DB_PASSWORD        # 👈 key inside that secret
